# Firmware size Optimizations
EXTRAFLAGS += -flto
MOUSEKEY_ENABLE = no
NKRO_ENABLE = no
SPACE_CADET_ENABLE = no
SPLIT_KEYBOARD = no
UNICODEMAP_ENABLE = no
COMBO_ENABLE = no
TAP_DANCE_ENABLE = no
COMMAND_ENABLE = no
